adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/read/',
         adminapp.TravelUsersListView.as_view(),
         name='users'),
    path('users/create/',
         adminapp.travel_user_create,
         name='user_create'),
    path('users/update/<int:pk>/',
         adminapp.travel_user_update,
         name='user_update'),
    path('users/delete/<int:pk>/',
         adminapp.travel_user_delete,
         name='user_delete'),

    path('countries/read/',
         adminapp.countries,
         name='countries'),
    path('countries/create/',
         adminapp.CountryCreateView.as_view(),
         name='country_create'),
    path('countries/update/<int:pk>/',
         adminapp.CountryUpdateView.as_view(),
         name='country_update'),
    path('countries/delete/<int:pk>/',
         adminapp.CountryDeleteView.as_view(),
         name='country_delete'),

    path('accommodation/read/countries/<int:pk>/',
         adminapp.accommodations,
         name='accommodations'),
    path('accommodation/create/countries/<int:pk>/',
         adminapp.accommodation_create,
         name='accommodation_create'),
    path('accommodation/update/<int:pk>/',
         adminapp.accommodation_update,
         name='accommodation_update'),
    path('accommodation/read/<int:pk>/',
         adminapp.AccommodationDetailView.as_view(),
         name='accommodation_read'),
    path('accommodation/delete/<int:pk>/',
         adminapp.accommodation_delete,
         name='accommodation_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/',
         authapp.login,
         name='login'),
    path('logout/',
         authapp.logout,
         name='logout'),
    path('register/',
         authapp.register,
         name='register'),
    path('edit/',
         authapp.edit,
         name='edit'),
]

market_prj/urls.py
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    path('admin/',
         include('adminapp.urls', namespace='admin')),
    path('',
         mainapp.main,
         name='main'),
    path('list_of_accommodations/',
         include('mainapp.urls', namespace='acc')),
    path('auth/',
         include('authapp.urls', namespace='auth')),
    path('',
         include('social_django.urls', namespace='social')),
    path('basket/',
         include('basketapp.urls', namespace='basket')),
    path('order/',
         include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import TravelUser
from authapp.forms import TravelUserEditForm
from mainapp.models import ListOfCountries
from mainapp.models import Accommodation


class TravelUserAdminEditForm(TravelUserEditForm):
    """Форма редактирования параметров пользователя"""

    class Meta:
        model = TravelUser
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control-sm'
            field.help_text = ''


class ListOfCountriesEditForm(forms.ModelForm):
    """Форма редактирования параметров стран"""

    class Meta:
        model = ListOfCountries
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class AccommodationEditForm(forms.ModelForm):
    """Форма редактирования параметров услуг компании"""

    class Meta:
        model = Accommodation
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = ''
            field.help_text = ''

adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from mainapp.models import Accommodation, ListOfCountries
from authapp.models import TravelUser
from authapp.forms import TravelUserRegisterForm
from adminapp.forms import TravelUserAdminEditForm, AccommodationEditForm


class TravelUsersListView(ListView):
    """админка - список пользователей"""

    model = TravelUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def travel_user_create(request):
    """админка - создание пользователя"""

    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = TravelUserRegisterForm(request.POST,
                                           request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = TravelUserRegisterForm()

    content = {
        'title': title,
        'update_form': user_form,
    }

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def travel_user_update(request, pk):
    """админка - редактирование пользователя"""

    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(TravelUser, pk=pk)

    if request.method == 'POST':
        edit_form = TravelUserAdminEditForm(request.POST,
                                            request.FILES,
                                            instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update',
                                                args=[edit_user.pk]))
    else:
        edit_form = TravelUserAdminEditForm(instance=edit_user)

    content = {
        'title': title,
        'update_form': edit_form,
    }

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def travel_user_delete(request, pk):
    """админка - удаление пользователя"""

    title = 'пользователи/удаление'
    user = get_object_or_404(TravelUser, pk=pk)

    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {
        'title': title,
        'user_to_delete': user,
    }

    return render(request, 'adminapp/user_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def countries(request):
    """админка - список стран"""

    title = 'админка/страны'
    countries_list = ListOfCountries.objects.all()

    content = {
        'title': title,
        'objects': countries_list
    }

    return render(request, 'adminapp/countries.html', content)


class CountryCreateView(CreateView):
    """админка - создание страны"""

    model = ListOfCountries
    template_name = 'adminapp/country_update.html'
    success_url = reverse_lazy('admin:countries')
    fields = '__all__'


class CountryUpdateView(UpdateView):
    """админка - редактирование страны"""

    model = ListOfCountries
    template_name = 'adminapp/country_update.html'
    success_url = reverse_lazy('admin:countries')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'страны/редактирование'
        return context


class CountryDeleteView(DeleteView):
    """админка - удаление страны"""

    model = ListOfCountries
    template_name = 'adminapp/country_delete.html'
    success_url = reverse_lazy('admin:countries')

    def form_valid(self, form):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.success_url)


@user_passes_test(lambda u: u.is_superuser)
def accommodations(request, pk):
    """админка - список предложений компании"""

    title = 'админка/размещение'
    country = get_object_or_404(ListOfCountries, pk=pk)
    accommodation_list = Accommodation.objects.filter(country__id=pk).order_by('name')

    content = {
        'title': title,
        'country': country,
        'objects': accommodation_list,
    }

    return render(request, 'adminapp/accommodations.html', content)


@user_passes_test(lambda u: u.is_superuser)
def accommodation_create(request, pk):
    """админка - создание нового предложения"""

    title = 'размещение/создание'
    country = get_object_or_404(ListOfCountries, pk=pk)

    if request.method == 'POST':
        accommodation_form = AccommodationEditForm(request.POST,
                                                   request.FILES)
        if accommodation_form.is_valid():
            accommodation_form.save()
            return HttpResponseRedirect(reverse('admin:accommodations',
                                                args=(pk,)))

    else:
        accommodation_form = AccommodationEditForm(initial={'country': country})

    content = {
        'title': title,
        'update_form': accommodation_form,
        'country': country,
    }

    return render(request, 'adminapp/accommodation_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def accommodation_update(request, pk):
    """админка - редактирование предложения"""

    title = 'размещение/редактирование'
    edit_accommodation = get_object_or_404(Accommodation, pk=pk)

    if request.method == 'POST':
        accommodation_edit_form = AccommodationEditForm(request.POST,
                                                        request.FILES,
                                                        instance=edit_accommodation)
        if accommodation_edit_form.is_valid():
            accommodation_edit_form.save()
            return HttpResponseRedirect(reverse('admin:accommodation_update',
                                                args=(edit_accommodation.pk,)))

    else:
        accommodation_edit_form = AccommodationEditForm(instance=edit_accommodation)

    content = {
        'title': title,
        'update_form': accommodation_edit_form,
        'country': edit_accommodation.country,
    }

    return render(request, 'adminapp/accommodation_update.html', content)


class AccommodationDetailView(DetailView):
    """админка - карточка предложения компании"""

    model = Accommodation
    template_name = 'adminapp/accommodation_read.html'


@user_passes_test(lambda u: u.is_superuser)
def accommodation_delete(request, pk):
    """админка - удаление предложения"""

    title = 'размещение/удаление'
    accommodation = get_object_or_404(Accommodation, pk=pk)

    if request.method == 'POST':
        accommodation.is_active = False
        accommodation.save()
        return HttpResponseRedirect(reverse('admin:accommodations',
                                            args=[accommodation.country.pk]))
    content = {
        'title': title,
        'accommodation_to_delete': accommodation,
    }

    return render(request, 'adminapp/accommodation_delete.html', content)

adminapp/templates/adminapp/accommodation_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mt-4 row justify-content-center">
        <div class="h2 col-auto text-center">
            Уверены, что хотите удалить {{ accommodation_to_delete.username }}
            {% if accommodation_to_delete.first_name %}
                ({{ accommodation_to_delete.first_name|title }}
                {% if accommodation_to_delete.last_name %}
                    {{ accommodation_to_delete.last_name|title }}
                {% endif %})
            {% endif %}?
        </div>
        <div class="row justify-content-center mt-4">
            <form action="{% url 'admin:accommodation_delete' accommodation_to_delete.pk %}"
                  method="post"
                  class="col-auto">
                {% csrf_token %}
                <input class="btn btn-danger"
                       type="submit"
                       value="удалить">
            </form>
            <button class="btn btn-success col-auto">
                <a href="{% url 'admin:accommodations' accommodation_to_delete.country.pk%}"
                   style="text-decoration: none; color:white">
                    отмена
                </a>
            </button>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/accommodation_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mt-4 mb-4 row justify-content-center">
        <div class="text-center">
            Продукт
            <strong>
                {{ object.category.name|title }} {{ object.name|title }}
            </strong>
        </div>
        <img src="/media/{{ object.image|default:'accommodation_img/default.jpg' }}"
             alt="{{ object.name }}"
             style="width: 800px">
        <div class="mt-4 text-center">
            <p><b>цена: </b>{{ object.price }} руб.</p>
            <p><b>количество ночей: </b>{{ object.availability }}</p>
            <p><b>в каталоге: </b>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <button>
                <a href="{% url 'admin:accommodation_update' object.pk %}"
                   style="text-decoration: none">
                    редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'admin:accommodation_delete' object.pk %}"
                   style="text-decoration: none">
                    удалить
                </a>
            </button>
            <button>
                <a href="{% url 'admin:accommodations' object.country.pk %}"
                   style="text-decoration: none">
                    назад
                </a>
            </button>
        </div>
        <div class="text-center mt-4">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <b>подробная информация</b>
            <p>{{ object.short_desc }}</p>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/accommodation_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mt-4 d-flex flex-column align-items-center">
        <form class="col-auto"
              method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input class="btn btn-primary"
                   type="submit"
                   value="сохранить">
        </form>
        <button class="mt-4 mb-4 btn btn-danger">
            <a href="{% url 'admin:accommodations' country.pk %}"
               style="text-decoration: none; color: white">
                к списку размещений
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/accommodations.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load tagz %}

{% block content %}
    <div class="mt-4 mb-4 row justify-content-center">
        <button class="btn btn-danger col-auto">
            <a href="{% url 'admin:accommodation_create' country.pk %}"
               style="text-decoration: none; color: white">
                новый продукт
            </a>
        </button>
        {% for object in objects %}
            <div class="row mt-4 justify-content-around align-items-center"
                 style="{% if not object.is_active %}opacity: 50%{% endif %}">
                <img src="{{ object.image | media_acc }}"
                     alt="{{ object.name }}"
                     style="width: 500px">
                <div class="col-auto text-center">
                    {{ object.name|title }}
                    <div class="row mt-2 justify-content-center gap-2">
                        <button class="col-auto">
                            <a href="{% url 'admin:accommodation_read' object.pk %}"
                               style="text-decoration: none">
                                подробнее
                            </a>
                        </button>
                        <button class="col-auto">
                            <a href="{% url 'admin:accommodation_update' object.pk %}"
                               style="text-decoration: none">
                                редактировать
                            </a>
                        </button>
                        <button class="col-auto">
                            <a href="{% url 'admin:accommodation_delete' object.pk %}"
                               style="text-decoration: none">
                                удалить
                            </a>
                        </button>
                        <div class="row mt-3">
                            <p><b>цена:</b> {{ object.price }} руб.</p>
                            <p><b>количество:</b> {{ object.availability }}</p>
                        </div>
                    </div>
                </div>
                <div class="mt-2 text-center">
                    {{ object.short_desc }}
                </div>
                <hr class="mt-2">
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/base.html
<!doctype html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block title %}
            <title>TravelMarket</title>
        {% endblock %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
        crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="mt-4 h2 text-center">
                Админка
            </div>
            {% block menu %}
                <div class="mt-4">
                    {% include 'adminapp/includes/inc_menu.html' %}
                </div>
            {% endblock %}

            {% block content %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    </body>
</html>

adminapp/templates/adminapp/countries.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="mt-4 row justify-content-center">
    <button class="btn btn-danger col-auto">
      <a href="{% url 'admin:country_create' %}"
         style="text-decoration: none; color: white">
        новая страна
      </a>
    </button>
    {% for object in objects %}
      <div style="{% if not object.is_active %}opacity: 50%{% endif %}">
        <div class="mt-4 col-auto">
          {{ object.name|title }}
        </div>
        <div class="mt-2 col-auto">
          <button>
            <a href="{% url 'admin:accommodations' object.pk %}"
               style="text-decoration: none">
              размещения
            </a>
          </button>
          <button>
            <a href="{% url 'admin:country_update' object.pk %}"
               style="text-decoration: none">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:country_delete' object.pk %}"
               style="text-decoration: none">
              удалить
            </a>
          </button>
        </div>
        <div class="mt-2 col-auto">
          {{ object.description }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/country_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="h2 col-auto text-center mt-4">
        <div class="col-auto text-center">
            Уверены, что хотите удалить страну <strong>
            {{ country_to_delete.name }}</strong>?
        </div>
        <div class="row justify-content-center mt-4">
            <form action="{% url 'admin:country_delete' object.pk %}"
                  method="post"
                  class="col-auto">
                {% csrf_token %}
                <input class="btn btn-danger"
                       type="submit"
                       value="удалить">
            </form>
            <button class="btn btn-success col-auto">
                <a href="{% url 'admin:countries' %}"
                   style="text-decoration: none; color: white">
                    отмена
                </a>
            </button>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/country_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mt-4 d-flex flex-column align-items-center">
        <form class="col-auto"
              method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary"
                   type="submit"
                   value="сохранить">
        </form>
        <button class="mt-4 mb-4 btn btn-danger">
            <a href="{% url 'admin:countries' %}"
               style="text-decoration: none; color: white">
                к списку стран
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mt-4 row justify-content-center">
        <div class="h2 col-auto text-center">
            Уверены, что хотите удалить {{ user_to_delete.username }}
            {% if user_to_delete.first_name %}
                <b>({{ user_to_delete.first_name|title }}</b>
                    {% if user_to_delete.last_name %}
                        <b>{{ user_to_delete.last_name|title }}</b>
                    {% endif %})
            {% endif %}?
        </div>
        <div class="row justify-content-center mt-4">
            <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
                  method="post"
                  class="col-auto">
                {% csrf_token %}
                <input class="btn btn-danger"
                       type="submit"
                       value="удалить">
            </form>
            <button class="btn btn-success col-auto">
                <a href="{% url 'admin:users' %}"
                   style="text-decoration: none; color:white">
                    отмена
                </a>
            </button>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mt-4 d-flex flex-column align-items-center">
        <form method="post"
              enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="btn btn-primary"
               type="submit"
               value="сохранить">
        </form>
        <button class="mt-4 mb-4 btn btn-danger">
            <a href="{% url 'admin:users' %}"
               style="text-decoration: none; color: white">
                к списку пользователей
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="text-center">
    <button class="mt-4 btn btn-danger">
      <a href="{% url 'admin:user_create' %}"
         style="text-decoration: none; color: white">
        новый пользователь
      </a>
    </button>
  </div>
  <div class="mt-4 row justify-content-around">
    {% for object in object_list %}
      <div class="col-auto mt-4 mb-4" style="{% if not object.is_active %}opacity: 50%{% endif %}">
        <img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
             alt="{{ object.username }}"
             style="width: 200px"
             class="row">
        <div class="mt-2">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href="{% url 'admin:user_update' object.pk %}"
               style="text-decoration: none">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:user_delete' object.pk %}"
               style="text-decoration: none">
              удалить
            </a>
          </button>
        </div>
        <div>
          <p><strong>{{ object.username }}</strong></p>
          <p>{% if object.first_name %}
            <b>{{ object.first_name|title }}</b>
              {% if object.last_name %}
                <b>{{ object.last_name|title }}</b>
              {% endif %}
            {% endif %}
          </p>
        </div>
        <div>
          age: {{ object.age }} лет
        </div>
        <div>
          email: {{ object.email }}
        </div>
        <div>
          logged: {{ object.last_login }}
        </div>
      </div>
    {% endfor%}
    </div>
{% endblock %}