authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/',
         authapp.login,
         name='login'),
    path('logout/',
         authapp.logout,
         name='logout'),
    path('register/',
         authapp.register,
         name='register'),
    path('edit/',
         authapp.edit,
         name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('',
         basketapp.basket,
         name='view'),
    path('add/<int:pk>/',
         basketapp.basket_add,
         name='add'),
    path('remove/<int:pk>/',
         basketapp.basket_remove,
         name='remove'),
    path('edit/<int:pk>/<int:nights>/',
         basketapp.basket_edit,
         name='edit'),
]

mainapp/urls.py
from django.urls import path
from django.urls import include
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('',
         mainapp.accommodations,
         name='index'),
    path('auth/',
         include('authapp.urls', namespace='auth')),
    path('accommodation_details/<int:pk>/',
         mainapp.accommodation,
         name='accommodation'),
]

market_prj/urls.py
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    path('admin/',
         include('adminapp.urls', namespace='admin')),
    path('',
         mainapp.main,
         name='main'),
    path('list_of_accommodations/',
         include('mainapp.urls', namespace='acc')),
    path('auth/',
         include('authapp.urls', namespace='auth')),
    path('',
         include('social_django.urls', namespace='social')),
    path('basket/',
         include('basketapp.urls', namespace='basket')),
    path('order/',
         include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


class ListOfCountries(models.Model):
    name = models.CharField(verbose_name='имя',
                            max_length=64,
                            unique=True)
    description = models.TextField(verbose_name='описание',
                                   blank=True)
    is_active = models.BooleanField(verbose_name='активна',
                                    default=True)

    def __str__(self):
        return self.name


class Regions(models.Model):
    country = models.ForeignKey(ListOfCountries,
                                on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя',
                            max_length=64,
                            unique=True)
    description = models.TextField(verbose_name='описание',
                                   blank=True)
    is_active = models.BooleanField(verbose_name='активна',
                                    default=True)

    def __str__(self):
        return self.name


class Accommodation(models.Model):
    country = models.ForeignKey(ListOfCountries,
                                on_delete=models.CASCADE)
    region = models.ForeignKey(Regions,
                               on_delete=models.CASCADE)
    name = models.CharField(verbose_name='название проживания',
                            max_length=128,
                            unique=True)
    image = models.ImageField(upload_to='accommodation_img',
                              blank=True)
    short_desc = models.TextField(verbose_name='краткое описание продукта',
                                  max_length=300,
                                  blank=True)
    description = models.TextField(verbose_name='описание продукта',
                                   max_length=1000,
                                   blank=True)
    availability = models.PositiveIntegerField(verbose_name='количество свободных номеров')
    price = models.DecimalField(verbose_name='цена',
                                max_digits=8,
                                decimal_places=2,
                                default=0)
    room_desc = models.TextField(verbose_name='краткое описание комнаты',
                                 max_length=300,
                                 blank=True)
    is_active = models.BooleanField(verbose_name='активна',
                                    default=True)

    @staticmethod
    def get_items(accommodation):
        return accommodation.objects.filter(is_active=True).order_by('country',
                                                                     'regions',
                                                                     'name')

    def __str__(self):
        return f'{self.name} ({self.country.name})'

mainapp/views.py
from random import sample
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .models import Accommodation


def main(request):
    title = 'главная'

    list_of_accommodations = Accommodation.objects.filter(is_active=True)

    hot_accommodation = sample(list(list_of_accommodations), 1)[0]

    content = {
        'title': title,
        'hot_accommodation': hot_accommodation,
    }

    return render(request, 'mainapp/index.html', content)


def accommodations(request):
    title = 'размещение'

    list_of_accommodations = Accommodation.objects.filter(is_active=True)

    content = {
        'title': title,
        'list_of_accommodations': list_of_accommodations,
    }

    return render(request, 'mainapp/accommodations.html', content)


def accommodation(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'accommodation': get_object_or_404(Accommodation, pk=pk),
    }

    return render(request, 'mainapp/accommodation_details.html', content)

mainapp/templates/mainapp/accommodation_details.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-4">
        <div class="d-flex flex-wrap text-center justify-content-center">
            <img src="/media/{{ accommodation.image }}"
                 class="mt-2" alt="Responsive image"
                 style="height: 300px">
            <div class="d-flex flex-column flex-grow-1">
                <div class="mt-4">
                    <h1>{{ accommodation.name|title }}</h1>
                    <p>месторасположение: {{ accommodation.region|title }}</p>
                    <p>стоимость за сутки: {{ accommodation.price }}</p>
                </div>
                <div class="mt-3">
                    <button class="btn  btn-danger">
                        <a style="color: white; text-decoration: none"
                           href="{% url 'basket:add' accommodation.pk %}">
                            Забронировать
                        </a>
                    </button>
                </div>
            </div>
        </div>
        <div class="mt-4">
            <h3>Описание</h3>
            {{ accommodation.description }}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/accommodations.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-3">
        <div class="row justify-content-center gap-1">
            {% for offer in list_of_accommodations %}
                <div class="card text-center"
                     style="width: 16rem">
                    <img src="/media/{{ offer.image|default:'accommodation_img/default.jpg' }}"
                         class="card-img-top pt-2"
                         alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ offer.name|title }}</h5>
                        <p class="card-text">{{ offer.region|title }}</p>
                        <p class="card-text">{{ offer.price }} за сутки.</p>
                        <a href="{% url 'acc:accommodation' offer.pk %}"
                           class="btn btn-danger">
                            Подробнее
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/base.html
<!doctype html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block title %}
            <title>TravelMarket</title>
        {% endblock %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
              crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            {% block menu %}
                {% include 'mainapp/includes/inc_menu.html' %}
            {% endblock %}

            {% block content %}
            {% endblock %}

            {% block footer %}
                {% include 'mainapp/includes/inc_footer.html' %}
            {% endblock %}
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    </body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div>
        <div id="carouselFade"
             class="carousel slide carousel-fade"
             data-bs-ride="true">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'img/thai.jpg' %}"
                         class="d-block w-100"
                         alt="thai">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/beach.jpg' %}"
                         class="d-block w-100"
                         alt="beach">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/sands.jpg' %}"
                         class="d-block w-100"
                         alt="sands">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/hawaii.jpg' %}"
                         class="d-block w-100"
                         alt="hawaii">
                </div>
            </div>
            <button class="carousel-control-prev"
               role="button"
               data-bs-target="#carouselFade"
               data-bs-slide="prev">
                <span class="carousel-control-prev-icon"
                      aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next"
               role="button"
               data-bs-target="#carouselFade"
               data-bs-slide="next">
                <span class="carousel-control-next-icon"
                      aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        <div class="card mt-4 text-center">
            <div class="card-header">
                Отдых, который Вы заслужили
            </div>
            <div class="card-body">
                <div class="card-text">
                    Мы собрали лучшие предложения для Вас
                </div>
                <a class="btn btn-danger mt-4"
                   href="{% url 'acc:index' %}">
                    Смотреть размещение
                </a>
            </div>
        </div>
        <div class="card mt-4 text-center">
            <div class="row g-0">
                <div class="col-md-4">
                    <img class="img-fluid rounded-start"
                         src="/media/{{ hot_accommodation.image }}"
                         alt="hot_accommodation">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h2 class="card-title"
                            style="color: red">
                            Горячее предложение!
                        </h2>
                        <h3 class="card-text">
                            {{ hot_accommodation.name }}
                        </h3>
                        <h3 class="card-text">
                            {{ hot_accommodation.price }} руб.
                        </h3>
                        <a href="{% url 'acc:accommodation' hot_accommodation.pk %}"
                           class="mt-4 btn btn-primary">
                            подробнее
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}