authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/',
         authapp.login,
         name='login'),
    path('logout/',
         authapp.logout,
         name='logout'),
    path('register/',
         authapp.register,
         name='register'),
    path('edit/',
         authapp.edit,
         name='edit'),
]

market_prj/urls.py
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    path('admin/',
         include('adminapp.urls', namespace='admin')),
    path('',
         mainapp.main,
         name='main'),
    path('list_of_accommodations/',
         include('mainapp.urls', namespace='acc')),
    path('auth/',
         include('authapp.urls', namespace='auth')),
    path('',
         include('social_django.urls', namespace='social')),
    path('basket/',
         include('basketapp.urls', namespace='basket')),
    path('order/',
         include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path, re_path

app_name = "ordersapp"

urlpatterns = [
    path('',
         ordersapp.OrderList.as_view(),
         name='orders_list'),
    path('forming/complete/<int:pk>/',
         ordersapp.order_forming_complete,
         name='order_forming_complete'),
    path('create/',
         ordersapp.OrderItemsCreate.as_view(),
         name='order_create'),
    path('read/<int:pk>/',
         ordersapp.OrderRead.as_view(),
         name='order_read'),
    path('update/<int:pk>/',
         ordersapp.OrderItemsUpdate.as_view(),
         name='order_update'),
    path('delete/<int:pk>/',
         ordersapp.OrderDelete.as_view(),
         name='order_delete'),
]

ordersapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Accommodation


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNL'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PROCEEDED, 'оплачен'),
        (PAID, 'обрабатывается'),
        (READY, 'подтверждён размещением'),
        (CANCEL, 'отменён'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан',
                                   auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлён',
                                   auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен',
                                    default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.pk} '

    def get_total_nights(self):
        accommodations = self.orderitems.select_related()
        return sum(list(map(lambda x: x.nights, accommodations)))

    def get_total_cost(self):
        accommodation = self.orderitems.select_related()
        return sum(list(map(lambda x: x.nights * x.accommodation.price, accommodation)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.accommodation.availability += item.nights
            item.accommodation.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='orderitems',
                              on_delete=models.CASCADE)
    accommodation = models.ForeignKey(Accommodation,
                                      verbose_name='размещение',
                                      on_delete=models.CASCADE)
    nights = models.PositiveIntegerField(verbose_name='количество',
                                         default=0)

    @staticmethod
    def get_items(pk):
        return OrderItem.objects.filter(pk=pk).first()

    def get_accommodation_cost(self):
        return self.accommodation.price * self.nights

ordersapp/forms.py
from django import forms
from ordersapp.models import Order
from ordersapp.models import OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    model = OrderItem
    price = forms.CharField(label='цена',
                            required=False)
    exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm


class OrderList(ListView):
    """список заказов"""

    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    """создание заказа с товарными позициями"""

    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order,
                                             OrderItem,
                                             form=OrderItemForm,
                                             extra=1,
                                             fields='__all__')

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order,
                                                     OrderItem,
                                                     form=OrderItemForm,
                                                     extra=len(basket_items),
                                                     fields='__all__')
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['accommodation'] = basket_items[num].accommodation
                    form.initial['nights'] = basket_items[num].nights
                    form.initial['price'] = basket_items[num].accommodation.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()

            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderItemsUpdate(UpdateView):
    """редактирование заказа с товарными позициями"""

    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order,
                                             OrderItem,
                                             form=OrderItemForm,
                                             extra=0,
                                             fields='__all__')
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST,
                                              instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)

            for form in formset.forms:

                if form.instance.pk:
                    form.initial['price'] = form.instance.accommodation.price

            data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()

            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderRead(DetailView):
    """карточка заказа"""

    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


class OrderDelete(DeleteView):
    """удаление заказа"""

    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def accommodation_nights_update_save(sender, update_fields, instance, **kwargs):
    if update_fields == 'nights' or 'accommodation':

        if instance.pk:
            instance.accommodation.availability -= instance.nights - sender.get_items(instance.pk).nights
        else:
            instance.accommodation.availability -= instance.nights

        instance.accommodation.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def accommodation_nights_update_delete(sender, instance, **kwargs):
    instance.accommodation.availability += instance.nights
    instance.accommodation.save()

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
        <title>{{ title|title }}</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
    crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            {% block menu %}
                {% include 'mainapp/includes/inc_menu.html' %}
            {% endblock %}

            {% block content %}
            {% endblock %}

            {% block footer %}
                {% include 'mainapp/includes/inc_footer.html' %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
                crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <script src="{% static 'js/order_scripts.js' %}"></script>
    </body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mt-4 row justify-content-center">
       <div class="h3 text-center">
           Уверены, что хотите удалить?
       </div>
       <div class="mt-4 col-auto">
           {% include 'ordersapp/includes/inc_order_summary.html' %}
       </div>
    </div>
    <div class="col mt-4 text-center">
        <form action="{% url 'ordersapp:order_delete' object.pk %}"
          method="post">
            {% csrf_token %}
            <input class="btn btn-danger"
                   type="submit"
                   value="удалить">
            <button class="btn btn-success">
            <a style="color: white; text-decoration: none"
               href="{% url 'ordersapp:orders_list' %}">
                отмена
            </a>
        </button>
        </form>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load tagz %}

{% block content %}
    <div class="mt-4 row justify-content-around">
        <div class="mt-4 col-auto h4">
            {% include 'ordersapp/includes/inc_order_summary.html' %}
        </div>
        {% for item in object.orderitems.select_related %}
            <div class="mt-4 col-auto text-center">
                <img style="width: 300px"
                     src="{{ item.accommodation.image|media_acc }}"
                     alt="{{ item.accommodation.short_desc }}">
                <div class="mt-2 h5">
                    <span>{{ item.accommodation.country.name|title }}</span>
                    <span>{{ item.accommodation.name|title }}</span>
                    <span>{{ item.accommodation.price }}&nbspруб.</span>
                    <span>x {{ item.nights }}
                    {% if item.nights == 1 %} ночь
                    {% elif 1 < item.nights and item.nights < 5 %} ночи
                    {% else %} ночей
                    {% endif %}</span>
                    <span class="product_cost"> = {{ item.get_accommodation_cost }}&nbspруб.</span>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mt-4 d-flex flex-wrap justify-content-center">
        {% include 'ordersapp/includes/inc_order_actions.html' %}
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
    <div class="mt-4 row justify-content-center">
        <div class="mt-4 col-auto h4">
            {% include 'ordersapp/includes/inc_order_summary.html' %}
        </div>
        <div class="mt-4 order_form table">
            <form action=""
                  method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <table class="table">
                    {{ orderitems.management_form }}
                    {% for form in orderitems.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %}">
                                        {{ field.label|capfirst }}
                                    </th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr>
                            {% for field in form.visible_fields %}
                                <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %}">
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    {% if field.name != 'price' %}
                                        {% if field.name == 'accommodation' %}
                                            {% cache 3600 orderitemform_accommodation field.value %}
                                                {{ field }}
                                            {% endcache %}
                                        {% else %}
                                            {{ field }}
                                        {% endif %}
                                    {% else %}
                                        {% if field.value %}
                                            <span class="orderitems-{{forloop.parentloop.counter0}}-price">
                                                {{ field.value }}
                                            </span> руб.
                                        {% endif %}
                                    {% endif %}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
                <div class="mt-4 d-flex flex-wrap justify-content-center">
                    <button class="btn btn-outline-secondary me-2 mb-2"
                            style="color: black; width: 12em">
                        сохранить
                    </button>
                    {% include 'ordersapp/includes/inc_order_actions.html' %}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="h2 text-center mt-4">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.first_name|title }}
        {% else %}
            {{ user.username }}
        {% endif %}
    </div>
    <table class="table mt-4 table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Создан</th>
                <th scope="col">Обновлен</th>
                <th scope="col">Статус</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
                <tr>
                    <td>{{ item.pk }}</td>
                    <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a href="{% url 'ordersapp:order_read' item.pk %}">
                            посмотреть
                        </a><br>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:order_update' item.pk %}">
                                редактировать
                            </a><br>
                        {% endif %}
                        {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:order_delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <div class="text-center">
        <button class="btn btn-outline-success">
            <a style="color: black; text-decoration: none"
               href="{% url 'main' %}">
                на главную
            </a>
        </button>
        <button class="btn btn-outline-success">
            <a style="color: black; text-decoration: none"
               href="{% url 'ordersapp:order_create' %}">
                новый
            </a>
        </button>
    </div>
{% endblock %}